package com.vultisig.wallet.models

import com.google.gson.annotations.SerializedName
import com.vultisig.wallet.R
import com.vultisig.wallet.data.models.ImageModel
import wallet.core.jni.CoinType

internal data class Coin(
    @SerializedName("chain")
    val chain: Chain,
    @SerializedName("ticker")
    val ticker: String,
    @SerializedName("logo")
    val logo: String,
    @SerializedName("address")
    val address: String,
    @SerializedName("decimals")
    val decimal: Int,
    @SerializedName("hexPublicKey")
    val hexPublicKey: String,
    @SerializedName("priceProviderId", alternate = ["priceProviderID"])
    val priceProviderID: String,
    @SerializedName("contractAddress")
    val contractAddress: String,
    @SerializedName("isNativeToken")
    val isNativeToken: Boolean,
) {
    val id: String
        get() = "${ticker}-${chain.id}"

    val coinType: CoinType
        get() = chain.coinType

}

internal fun Coin.AllowZeroGas(): Boolean {
    return this.chain == Chain.polkadot
}

internal object Coins {

    val wewe = Coin(
        chain = Chain.base,
        ticker = "WEWE",
        logo = "wewe",
        address = "",
        decimal = 18,
        hexPublicKey = "",
        priceProviderID = "",
        contractAddress = "0x6b9bb36519538e0C073894E964E90172E1c0B41F",
        isNativeToken = false,
    )
    val solana =  Coin(
        chain = Chain.solana,
        ticker = "SOL",
        logo = "sol",
        address = "",
        decimal = 9,
        hexPublicKey = "",
        priceProviderID = "solana",
        contractAddress = "",
        isNativeToken = true,
    )
    val SupportedCoins = listOf(
        wewe,
        Coin(
            chain = Chain.bitcoin,
            ticker = "BTC",
            logo = "btc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "bitcoin",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.bitcoinCash,
            ticker = "BCH",
            logo = "bch",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "bitcoin-cash",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.litecoin,
            ticker = "LTC",
            logo = "ltc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "litecoin",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.dogecoin,
            ticker = "DOGE",
            logo = "doge",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "dogecoin",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.dash,
            ticker = "DASH",
            logo = "dash",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "dash",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.thorChain,
            ticker = "RUNE",
            logo = "rune",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "thorchain",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.mayaChain,
            ticker = "CACAO",
            logo = "cacao",
            address = "",
            decimal = 10,
            hexPublicKey = "",
            priceProviderID = "cacao",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.mayaChain,
            ticker = "MAYA",
            logo = "maya",
            address = "",
            decimal = 4,
            hexPublicKey = "",
            priceProviderID = "maya",
            contractAddress = "",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "ETH",
            logo = "eth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "usd-coin",
            contractAddress = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "tether",
            contractAddress = "0xdAC17F958D2ee523a2206206994597C13D831ec7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "UNI",
            logo = "uni",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "uniswap",
            contractAddress = "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "MATIC",
            logo = "matic",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "matic-network",
            contractAddress = "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "WBTC",
            logo = "wbtc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "wrapped-bitcoin",
            contractAddress = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "LINK",
            logo = "link",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "chainlink",
            contractAddress = "0x514910771af9ca656af840dff83e8264ecf986ca",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "FLIP",
            logo = "flip",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "chainflip",
            contractAddress = "0x826180541412d574cf1336d22c0c0a287822678a",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "TGT",
            logo = "tgt",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "thorwallet",
            contractAddress = "0x108a850856Db3f85d0269a2693D896B394C80325",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "FOX",
            logo = "fox",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "shapeshift-fox-token",
            contractAddress = "0xc770eefad204b5180df6a14ee197d99d808ee52d",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "DAI",
            logo = "dai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "dai",
            contractAddress = "0x6b175474e89094c44da98b954eedeac495271d0f",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "WETH",
            logo = "weth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "weth",
            contractAddress = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "YFI",
            logo = "yfi",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "yearn-finance",
            contractAddress = "0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "AAVE",
            logo = "aave",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "aave",
            contractAddress = "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "COMP",
            logo = "comp",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "compound-governance-token",
            contractAddress = "0xc00e94cb662c3520282e6f5717214004a7f26888",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "BAT",
            logo = "bat",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "basic-attention-token",
            contractAddress = "0x0d8775f648430679a709e98d2b0cb6250d2887ef",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "SNX",
            logo = "snx",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "havven",
            contractAddress = "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "BAL",
            logo = "bal",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "balancer",
            contractAddress = "0xba100000625a3754423978a60c9317c58a424e3d",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "SUSHI",
            logo = "sushi",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "sushi",
            contractAddress = "0x6b3595068778dd592e39a122f4f5a5cf09c90fe2",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "MKR",
            logo = "mkr",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "maker",
            contractAddress = "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "KNC",
            logo = "knc",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "kyber-network-crystal",
            contractAddress = "0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "GRT",
            logo = "grt",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "the-graph",
            contractAddress = "0xc944e90c64b2c07662a292be6244bdf05cda44a7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.ethereum,
            ticker = "PEPE",
            logo = "pepe",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "pepe",
            contractAddress = "0x6982508145454ce325ddbe47a25d4ec3d2311933",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "AVAX",
            logo = "avax",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "avalanche-2",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "usd-coin",
            contractAddress = "0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "BTC.b",
            logo = "BTC.b",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x152b9d0FdC40C096757F570A51E494bd4b943E50",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "sAVAX",
            logo = "savax",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "JOE",
            logo = "joe",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "PNG",
            logo = "png",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x60781C2586D68229fde47564546784ab3fACA982",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "WAVAX",
            logo = "wavax",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "aAvaUSDC",
            logo = "aAvaUSDC",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x625E7708f30cA75bfd92586e17077590C60eb4cD",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "BLS",
            logo = "bls",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x46B9144771Cb3195D66e4EDA643a7493fADCAF9D",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.avalanche,
            ticker = "COQ",
            logo = "coq",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x420FcA0121DC28039145009570975747295f2329",
            isNativeToken = false,
        ),
        solana,
        Coin(
            chain = Chain.bscChain,
            ticker = "BNB",
            logo = "bsc",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "binancecoin",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "tether",
            contractAddress = "0x55d398326f99059fF775485246999027B3197955",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "usd-coin",
            contractAddress = "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "DAI",
            logo = "dai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "WETH",
            logo = "weth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "AAVE",
            logo = "aave",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xfb6115445bff7b52feb98650c87f44907e58f802",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "COMP",
            logo = "comp",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x52ce071bd9b1c4b00a0b92d298c512478cad67e8",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "SUSHI",
            logo = "sushi",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x947950bcc74888a40ffa2593c5798f11fc9124c4",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "KNC",
            logo = "knc",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xfe56d5892bdffc7bf58f2e84be1b2c32d21c308b",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.bscChain,
            ticker = "PEPE",
            logo = "pepe",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x25d887ce7a35172c62febfd67a1856f20faebb00",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "ETH",
            logo = "eth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.base,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "usd-coin",
            contractAddress = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "DAI",
            logo = "dai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "dai",
            contractAddress = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "rETH",
            logo = "reth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "reth",
            contractAddress = "0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "ezETH",
            logo = "ezeth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ezETH",
            contractAddress = "0x2416092f143378750bb29b79eD961ab195CcEea5",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "PYTH",
            logo = "pyth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "pyth",
            contractAddress = "0x4c5d8A75F3762c1561D96f177694f67378705E98",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "OM",
            logo = "om",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "om",
            contractAddress = "0x3992B27dA26848C2b19CeA6Fd25ad5568B68AB98",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "W",
            logo = "w",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "w",
            contractAddress = "0xB0fFa8000886e57F86dd5264b9582b2Ad87b2b91",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "cbETH",
            logo = "cbeth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "cbETH",
            contractAddress = "0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "SNX",
            logo = "snx",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "SNX",
            contractAddress = "0x22e6966B799c4D5B13BE962E1D117b56327FDa66",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.base,
            ticker = "AERO",
            logo = "aero",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "AERO",
            contractAddress = "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "ETH",
            logo = "eth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "ARB",
            logo = "arbitrum",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "arbitrum",
            contractAddress = "0x912CE59144191C1204E64559FE8253a0e49E6548",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "TGT",
            logo = "tgt",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "thorwallet",
            contractAddress = "0x429fEd88f10285E61b12BDF00848315fbDfCC341",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "FOX",
            logo = "fox",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "shapeshift-fox-token",
            contractAddress = "0xf929de51D91C77E42f5090069E0AD7A09e513c73",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "USDT",
            contractAddress = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "USDC.e",
            logo = "usdc.e",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "USDC.e",
            contractAddress = "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "USDC",
            contractAddress = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "WBTC",
            logo = "wbtc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "WBTC",
            contractAddress = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "LINK",
            logo = "link",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "LINK",
            contractAddress = "0xf97f4df75117a78c1A5a0DBb814Af92458539FB4",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "DAI",
            logo = "dai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "DAI",
            contractAddress = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "UNI",
            logo = "uni",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "UNI",
            contractAddress = "0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "PEPE",
            logo = "pepe",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "PEPE",
            contractAddress = "0x25d887Ce7a35172C62FeBFD67a1856F20FaEbB00",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "GRT",
            logo = "grt",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "GRT",
            contractAddress = "0x9623063377AD1B27544C965cCd7342f7EA7e88C7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "ezETH",
            logo = "ezeth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ezETH",
            contractAddress = "0x2416092f143378750bb29b79eD961ab195CcEea5",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "PYTH",
            logo = "pyth",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "PYTH",
            contractAddress = "0xE4D5c6aE46ADFAF04313081e8C0052A30b6Dd724",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.arbitrum,
            ticker = "LDO",
            logo = "ldo",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "LDO",
            contractAddress = "0x13Ad51ed4F1B7e9Dc168d8a00cB3f4dDD85EfA60",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "ETH",
            logo = "eth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "OP",
            logo = "optimism",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "optimism",
            contractAddress = "0x4200000000000000000000000000000000000042",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "FOX",
            logo = "fox",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "shapeshift-fox-token",
            contractAddress = "0xf1a0da3367bc7aa04f8d94ba57b862ff37ced174",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "USDC.e",
            logo = "USDC.e",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "WBTC",
            logo = "wbtc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x68f180fcCe6836688e9084f035309E29Bf0A2095",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "LINK",
            logo = "link",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x350a791Bfc2C21F9Ed5d10980Dad2e2638ffa7f6",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "DAI",
            logo = "dai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "ezETH",
            logo = "ezeth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x2416092f143378750bb29b79eD961ab195CcEea5",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "PYTH",
            logo = "pyth",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x99C59ACeBFEF3BBFB7129DC90D1a11DB0E91187f",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.optimism,
            ticker = "LDO",
            logo = "ldo",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xFdb794692724153d1488CcdBE0C56c252596735F",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "MATIC",
            logo = "matic",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "matic-network",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "WETH",
            logo = "weth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "FOX",
            logo = "fox",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "shapeshift-fox-token",
            contractAddress = "0x65a05db8322701724c197af82c9cae41195b0aa8",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "USDT",
            logo = "usdt",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "BNB",
            logo = "bnb",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x3BA4c387f786bFEE076A58914F5Bd38d668B42c3",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "SOL",
            logo = "sol",
            address = "",
            decimal = 9,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xd93f7E271cB87c23AaA73edC008A79646d1F9912",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "USDC",
            logo = "usdc",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "USDC.e",
            logo = "USDC.e",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "BUSD",
            logo = "busd",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xdAb529f40E671A1D4bF91361c21bf9f0C9712ab7",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "WBTC",
            logo = "wbtc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "AVAX",
            logo = "avax",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x2C89bbc92BD86F8075d1DEcc58C7F4E0107f286b",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "SHIB",
            logo = "shib",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x6f8a06447Ff6FcF75d803135a7de15CE88C1d4ec",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.polygon,
            ticker = "LINK",
            logo = "link",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xb0897686c545045aFc77CF20eC7A532E3120E0F1",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "ETH",
            logo = "eth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "WETH",
            logo = "weth",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "ethereum",
            contractAddress = "0x4300000000000000000000000000000000000004",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "WBTC",
            logo = "wbtc",
            address = "",
            decimal = 8,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xF7bc58b8D8f97ADC129cfC4c9f45Ce3C0E1D2692",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "USDB",
            logo = "usdb",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x4300000000000000000000000000000000000003",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "BLAST",
            logo = "blast",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xb1a5700fA2358173Fe465e6eA4Ff52E36e88E2ad",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "MIM",
            logo = "mim",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x76DA31D7C9CbEAE102aff34D3398bC450c8374c1",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "bLOOKS",
            logo = "blooks",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x406F10d635be12ad33D6B133C6DA89180f5B999e",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "BAG",
            logo = "bag",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0xb9dfCd4CF589bB8090569cb52FaC1b88Dbe4981F",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "ZERO",
            logo = "zero",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x357f93E17FdabEcd3fEFc488a2d27dff8065d00f",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "AI",
            logo = "ai",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x764933fbAd8f5D04Ccd088602096655c2ED9879F",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "JUICE",
            logo = "juice",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x818a92bc81Aad0053d72ba753fb5Bc3d0C5C0923",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "OMNI",
            logo = "omni",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x9e20461bc2c4c980f62f1B279D71734207a6A356",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.blast,
            ticker = "DACKIE",
            logo = "dackie",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "",
            contractAddress = "0x47C337Bd5b9344a6F3D6f58C474D9D8cd419D8cA",
            isNativeToken = false,
        ),
        Coin(
            chain = Chain.cronosChain,
            ticker = "CRO",
            logo = "cro",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "crypto-com-chain",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.gaiaChain,
            ticker = "ATOM",
            logo = "atom",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "cosmos",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.kujira,
            ticker = "KUJI",
            logo = "kuji",
            address = "",
            decimal = 6,
            hexPublicKey = "",
            priceProviderID = "kujira",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.dydx,
            ticker = "DYDX",
            logo = "dydx",
            address = "",
            decimal = 18,
            hexPublicKey = "",
            priceProviderID = "dydx-chain",
            contractAddress = "",
            isNativeToken = true,
        ),
        Coin(
            chain = Chain.polkadot,
            ticker = "DOT",
            logo = "dot",
            address = "",
            decimal = 10,
            hexPublicKey = "",
            priceProviderID = "polkadot",
            contractAddress = "",
            isNativeToken = true,
        ),
    )

    fun getCoin(ticker: String, address: String, hexPublicKey: String, coinType: CoinType): Coin? {
        return SupportedCoins.find { it.ticker == ticker && it.coinType == coinType }
            ?.copy(address = address, hexPublicKey = hexPublicKey)

    }

    fun getCoinLogo(logoName: String): ImageModel {
        return when (logoName) {
            "btc" -> R.drawable.bitcoin
            "bch" -> R.drawable.bitcoincash
            "ltc" -> R.drawable.litecoin
            "doge" -> R.drawable.doge
            "dash" -> R.drawable.dash
            "rune" -> R.drawable.rune
            "eth" -> R.drawable.ethereum
            "sol" -> R.drawable.solana
            "cacao" -> R.drawable.cacao
            "maya" -> R.drawable.maya_token_02
            "usdc" -> R.drawable.usdc
            "usdt" -> R.drawable.usdt
            "link" -> R.drawable.link
            "uni" -> R.drawable.uni
            "matic" -> R.drawable.polygon
            "wbtc" -> R.drawable.wbtc
            "flip" -> R.drawable.chainflip
            "avax" -> R.drawable.avax
            "eth_optimism" -> R.drawable.eth_optimism
            "optimism" -> R.drawable.optimism
            "eth_arbitrum" -> R.drawable.eth_arbitrum
            "eth_polygon" -> R.drawable.polygon
            "eth_base" -> R.drawable.eth_base
            "bsc" -> R.drawable.bsc
            "eth_blast" -> R.drawable.eth_blast
            "blast" -> R.drawable.blast
            "eth_cro" -> R.drawable.eth_cro
            "cro" -> R.drawable.cro
            "arbitrum" -> R.drawable.arbitrum
            "kuji" -> R.drawable.kuji
            "atom" -> R.drawable.atom
            "dydx" -> R.drawable.dydx
            "polygon" -> R.drawable.polygon
            "tgt" -> R.drawable.tgt
            "fox" -> R.drawable.fox
            "dot" -> R.drawable.dot
            "wETH"->R.drawable.weth
            "wewe" -> R.drawable.wewe
            "omni" -> R.drawable.omni
            "pyth" -> R.drawable.pyth
            "snx" -> R.drawable.snx
            "sushi" -> R.drawable.sushi
            "yfi" -> R.drawable.yfi
            "mkr" -> R.drawable.mkr
            "pepe" -> R.drawable.pepe
            "reth" -> R.drawable.reth
            "shib" -> R.drawable.shib
            "w" -> R.drawable.w
            "aave" -> R.drawable.aave
            "bal" -> R.drawable.bal
            "bat" -> R.drawable.bat
            "bnb" -> R.drawable.bnb
            "busd" -> R.drawable.busd
            "comp" -> R.drawable.comp
            "grt" -> R.drawable.grt
            "mim" -> R.drawable.mim
            "ldo" -> R.drawable.ldo
            "dai" -> R.drawable.dai
            "knc" -> R.drawable.knc
            "aero" -> R.drawable.aero
            "bag" -> R.drawable.bag
            "blooks" -> R.drawable.blooks
            "cbeth" -> R.drawable.cbeth
            "coq" -> R.drawable.coq
            "dackie"->R.drawable.dackie
            "ezeth" -> R.drawable.ezeth
            "joe"->R.drawable.joe
            "juice"->R.drawable.juice
            "om"->R.drawable.om
            "png"->R.drawable.png
            "savax"->R.drawable.savax
            "usdb"->R.drawable.usdb
            "weth"->R.drawable.weth
            "zero"->R.drawable.zero

            else -> logoName
        }
    }
}