name: Vultisig Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: git submodule update
        run: git submodule update --init --recursive

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run debug unit tests
        run: ./gradlew :app:assembleDebugUnitTest

      - name: Run debug Android test
        run: ./gradlew :app:assembleDebugAndroidTest
